name: hytest_tc_workflow
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - aiohttp>=3.8.5
  - cartopy>=0.21.1
  - cdsapi>=0.6.1
  - dask>=2023.7.1
  - fsspec>=2023.6.0
  - h5py>=3.9.0
  - holoviews>=1.16.2
  - hvplot>=0.8.4
  - jupyterlab>=4.0.3
  - matplotlib>=3.7.2
  - panel>=1.2.0
  - rioxarray>=0.14.1
  - scipy>=1.11.1
  - xarray>=2023.7.0
  - xarray-einstats>=0.6.0
  - zipfile-deflate64>=0.2.0
  - pip
  - pip:
    - sciencebasepy>=2.0.13
    - xarray-regrid>=0.2.2
    - xesmf>=0.8
